apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
  labels:
    component: kube-controller-manager
    tier: control-plane
spec:
  hostNetwork: true
  containers:
  - name: kube-controller-manager
    image: ${hyperkube_image}
    command:
    - /hyperkube
    - controller-manager
    - --address=127.0.0.1
    - --leader-elect
    - --master=127.0.0.1:8080
    - --root-ca-file=/etc/kubernetes/tls/ca.crt
    - --service-account-private-key-file=/etc/kubernetes/tls/service-account.key
    - --cluster-signing-cert-file=/etc/kubernetes/tls/ca.crt
    - --cluster-signing-key-file=/etc/kubernetes/tls/ca.key
    - --insecure-experimental-approve-all-kubelet-csrs-for-group=system:kubelet-bootstrap
    - --cloud-provider=external
    - --v=${verbosity}
    livenessProbe:
      httpGet:
        path: /healthz
        port: 10252
        host: 127.0.0.1
      initialDelaySeconds: 15
      timeoutSeconds: 15
      failureThreshold: 8
    resources:
      requests:
        cpu: 200m
    volumeMounts:
    - name: etckubernetes
      readOnly: true
      mountPath: /etc/kubernetes
    - name: etcsslcerts
      readOnly: true
      mountPath: /etc/ssl/certs
  volumes:
  - name: etckubernetes
    hostPath:
      path: /etc/kubernetes
  - name: etcsslcerts
    hostPath:
      path: /etc/ssl/certs
  